/*
 * word.h
 *
 *
 * @date 17-03-2019
 * @author Teddy DIDE
 * @version 1.00
 * Word Wrapper generated by gensources. Allows to control MS Word.
 */

#ifndef _WORD_H_
#define _WORD_H_
#include <windows.h>
#include "word_wrapper.h"

namespace word
{
	class Word
	{

	private:
		static Application* m_application;

	public:
		static bool Initialize();
		static bool UnInitialize();
		static Application* getApplication();
	};

}

#endif