/** 
 * SqliteDataIntParameter.hpp
 *
 *
 * @date: 19-07-2012
 * @author: Teddy DIDÉ
 * @version: 2.00
 * @brief: Project generated by gensources
 */

#ifndef _SQLITE_DATA_INTPARAMETER_HPP_
#define _SQLITE_DATA_INTPARAMETER_HPP_

#include "databaseparameter.hpp"

NAMESPACE_BEGIN(data_access)

using namespace log4cpp;
using namespace enc;

template <class EncodingT>
class _DataIntParameter
: public _DataBaseParameter<EncodingT>
{ 
private:
	int m_value;
	Category* m_logger;
	
public:
	_DataIntParameter(int value);
	
	// Complete Statement
	virtual bool 
	complete(_DataStatement<EncodingT>& statement, int index) const;
};

typedef _DataIntParameter<ucs>        UniDataIntParameter;
typedef _DataIntParameter<ansi>       DataIntParameter;

NAMESPACE_END

#include "dataintparameter_impl.hpp"
#endif
