/*
 * TimeOutInterpreter.hpp
 *
 *
 * @date 21-06-2016
 * @author Teddy DIDE
 * @version 1.00
 * Debug Interpreter generated by gensources.
 */

#ifndef _TIMEOUT_INTERPRETER_H_
#define _TIMEOUT_INTERPRETER_H_

#include "config.hpp"
#include "macros.hpp"
#include "String.hpp"
#include "Array.hpp"


#define A(str) encode<EncodingT,ansi>(str)
#define C(str) encode<ansi,EncodingT>(str)

using namespace boost;

NAMESPACE_BEGIN(interp)

	template <class EncodingT>
	class TimeOutInterpreter
	: public Base<EncodingT>
	{
	private:

		void tidyValue();

	public:
		TimeOutInterpreter();

		~TimeOutInterpreter();

		virtual typename EncodingT::string_t toString() const;

		virtual shared_ptr< Base<EncodingT> > clone() const;

		virtual typename EncodingT::string_t getClassName() const;

		virtual shared_ptr< Base<EncodingT> > invoke(const typename EncodingT::string_t& method, std::vector< shared_ptr< Base<EncodingT> > >& params);

		shared_ptr< Base<EncodingT> > getINFINITE() const;

		FACTORY_BEGIN_REGISTER
			CLASS_KEY_REGISTER  ( TimeOutInterpreter, C("TimeOut") );
			METHOD_KEY_REGISTER ( TimeOutInterpreter, shared_ptr< Base<EncodingT> >, getINFINITE, const_t, C("TimeOut::INFINITE") );
		FACTORY_END_REGISTER

		FACTORY_BEGIN_UNREGISTER
			CLASS_KEY_UNREGISTER  ( C("TimeOut") );
			METHOD_KEY_UNREGISTER ( C("TimeOut::INFINITE") );
		FACTORY_END_UNREGISTER
	};

NAMESPACE_END

#undef A
#undef C
#include "TimeOutInterpreter_impl.hpp"

#endif