/* 
 * debugFileInfoAccess.hpp
 *
 *
 * @date 25-06-2020
 * @author Teddy DIDE
 * @version 1.00
 * cppBase generated by gensources.
 */

#ifndef _DEBUGFILEINFO_ACCESS_HPP_
#define _DEBUGFILEINFO_ACCESS_HPP_

#include <boost/scoped_ptr.hpp>
#include <memory>
#include <boost/signals2.hpp>
#include <boost/any.hpp>
#include "cppBaseExport.hpp"
#include "debugFileInfo.hpp"

#define A(str) encode<EncodingT,ansi>(str)
#define C(str) encode<ansi,EncodingT>(str)

NAMESPACE_BEGIN(data_access)

using namespace entity; 

/// Represents an access class for DebugFileInfo object.
/// This class is used to manage DebugFileInfo entity in database.
template <class EncodingT>
class CPPBASE_API  _DebugFileInfoAccess {
private :
	std::list< boost::shared_ptr< _DebugFileInfo<EncodingT> > > m_backup;
	// Is a transaction in progress before queries ?
	bool m_transactionOwner;
	static _DebugFileInfoAccess<EncodingT>* m_instance; 

public:
	typedef boost::signals2::signal<void (operation_access_t, typename EncodingT::string_t const&, boost::any const&)>  signal_t;
	typedef boost::signals2::signal<void (operation_access_t)>  signal_transaction_t;
	typedef boost::signals2::connection  connection_t;

private:
	signal_t m_insertSignal;
	signal_t m_updateSignal;
	signal_t m_deleteSignal;
	signal_transaction_t m_transactionSignal;

private:
	/** Creates a new element DebugFileInfoAccess.
	*/
	_DebugFileInfoAccess();
	/** Releases the DebugFileInfoAccess object.
	*/
	~_DebugFileInfoAccess();
	Category*	m_logger;

protected :
public :
	/** Returns DebugFileInfoAccess object.
	@return Instance of DebugFileInfoAccess.
	*/
	 static _DebugFileInfoAccess<EncodingT>* getInstance();
	/** Returns DebugFileInfo objects from database.
	@param filter Condition allowing to filter data.
	@return List of DebugFileInfo objects.
	*/
	 std::vector< boost::shared_ptr< _DebugFileInfo<EncodingT> > > getManyDebugFileInfos(typename EncodingT::string_t const&  filter) const;
	/** Returns all DebugFileInfo objects from database.
	@return List of DebugFileInfo objects.
	*/
	 std::vector< boost::shared_ptr< _DebugFileInfo<EncodingT> > > getAllDebugFileInfos() const;
	/** Returns DebugFileInfo object from database.
	@param identifier 
	@return The DebugFileInfo object.
	*/
	 boost::shared_ptr< _DebugFileInfo<EncodingT> > getOneDebugFileInfo(long long identifier) const;
	/** Returns DebugFileInfo objects from database. Data are locked for update.
	@param filter Condition allowing to filter data.
	@param nowait Asynchonous call.
	@return List of DebugFileInfo objects.
	*/
	 std::vector< boost::shared_ptr< _DebugFileInfo<EncodingT> > > selectManyDebugFileInfos(typename EncodingT::string_t const&  filter, bool nowait = false, bool addition = false);
	/** Returns DebugFileInfo object from database. Data are locked for update.
	@param identifier 
	@param nowait Asynchonous call.
	@return The DebugFileInfo object.
	*/
	 boost::shared_ptr< _DebugFileInfo<EncodingT> > selectOneDebugFileInfo(long long identifier, bool nowait = false, bool addition = false);
	/** Returns whether the data <i>DebugFileInfo</i> are selected.
	@param o The DebugFileInfo object.
	@return True if the data <i>DebugFileInfo</i> are selected.
	*/
	 bool isSelectedDebugFileInfo(boost::shared_ptr< _DebugFileInfo<EncodingT> > o) const;
	/** Cancel the selection. The DebugFileInfo object cannot be updated or deleted from database.
	*/
	 void cancelSelection();
	/** Fills textFile data from database.
	@param o The DebugFileInfo object.
	*/
	 void fillTextFile(boost::shared_ptr< _DebugFileInfo<EncodingT> > o);
	/** Fills debugFunctionInfo data from database.
	@param o The DebugFileInfo object.
	@param nowait Asynchronous call.
	*/
	 void fillAllDebugFunctionInfos(boost::shared_ptr< _DebugFileInfo<EncodingT> > o, bool nowait = false);
	/** Fills debugFunctionInfo data from database.
	@param o The DebugFileInfo object.
	@param identifier 
	@param nowait Asynchronous call.
	*/
	 void fillOneDebugFunctionInfo(boost::shared_ptr< _DebugFileInfo<EncodingT> > o, long long identifier, bool nowait = false);
	/** Fills debugFunctionInfo data from database.
	@param o The DebugFileInfo object.
	@param filter Condition allowing to filter data.
	@param nowait Asynchonous call.
	*/
	 void fillManyDebugFunctionInfos(boost::shared_ptr< _DebugFileInfo<EncodingT> > o, typename EncodingT::string_t const&  filter, bool nowait = false);
	/** Fills debugStubInfo data from database.
	@param o The DebugFileInfo object.
	@param nowait Asynchronous call.
	*/
	 void fillAllDebugStubInfos(boost::shared_ptr< _DebugFileInfo<EncodingT> > o, bool nowait = false);
	/** Fills debugStubInfo data from database.
	@param o The DebugFileInfo object.
	@param identifier 
	@param nowait Asynchronous call.
	*/
	 void fillOneDebugStubInfo(boost::shared_ptr< _DebugFileInfo<EncodingT> > o, long long identifier, bool nowait = false);
	/** Fills debugStubInfo data from database.
	@param o The DebugFileInfo object.
	@param filter Condition allowing to filter data.
	@param nowait Asynchonous call.
	*/
	 void fillManyDebugStubInfos(boost::shared_ptr< _DebugFileInfo<EncodingT> > o, typename EncodingT::string_t const&  filter, bool nowait = false);
	/** Returns whether DebugFileInfo data are altered from database.
	@param o The DebugFileInfo object.
	@return True if data DebugFileInfo have been altered.
	*/
	 bool isModifiedDebugFileInfo(boost::shared_ptr< _DebugFileInfo<EncodingT> > o) const;
	/** Updates DebugFileInfo data to database.
	@param o The DebugFileInfo object.
	*/
	 void updateDebugFileInfo(boost::shared_ptr< _DebugFileInfo<EncodingT> > o);
	/** Inserts DebugFileInfo data to database.
	@param o The DebugFileInfo object.
	*/
	 void insertDebugFileInfo(boost::shared_ptr< _DebugFileInfo<EncodingT> > o);
	/** Deletes DebugFileInfo data to database.
	@param o The DebugFileInfo object.
	*/
	 void deleteDebugFileInfo(boost::shared_ptr< _DebugFileInfo<EncodingT> > o);
	/** Add signal for DebugFileInfo insertion.
	@param subscriber The observer
	@return The connection
	*/
	 connection_t addInsertSignal(typename signal_t::slot_function_type subscriber);
	/** Add signal for DebugFileInfo update.
	@param subscriber The observer
	@return The connection
	*/
	 connection_t addUpdateSignal(typename signal_t::slot_function_type subscriber);
	/** Add signal for DebugFileInfo deletion.
	@param subscriber The observer
	@return The connection
	*/
	 connection_t addDeleteSignal(typename signal_t::slot_function_type subscriber);
	/** Add signal for DebugFileInfo transaction result.
	@param subscriber The observer
	@return The connection
	*/
	 connection_t addTransactionSignal(typename signal_transaction_t::slot_function_type subscriber);
	/** Remove signal for DebugFileInfo insertion.
	@param connection The connection
	*/
	 void removeInsertSignal(connection_t connection);
	/** Remove signal for DebugFileInfo update.
	@param connection The connection
	*/
	 void removeUpdateSignal(connection_t connection);
	/** Remove signal for DebugFileInfo deletion.
	@param connection The connection
	*/
	 void removeDeleteSignal(connection_t connection);
	/** Remove signal for DebugFileInfo transaction result.
	@param connection The connection
	*/
	 void removeTransactionSignal(connection_t connection);
};

typedef _DebugFileInfoAccess<ucs> UniDebugFileInfoAccess;
typedef _DebugFileInfoAccess<ansi> DebugFileInfoAccess;

NAMESPACE_END

#undef C
#undef A

#if !defined(HAS_CPPBASE_DLL) || defined(BUILD_CPPBASE_DLL)
#include "debugFileInfoAccess_impl.hpp"
#endif // !defined(HAS_CPPBASE_DLL) || defined(BUILD_CPPBASE_DLL)

#endif
