/*
 * IDiaSourceFilePtrInterpreter.hpp
 *
 *
 * @date 21-06-2016
 * @author Teddy DIDE
 * @version 1.00
 * Pdb Interpreter generated by gensources.
 */

#ifndef _IDIASOURCEFILEPTR_INTERPRETER_H_
#define _IDIASOURCEFILEPTR_INTERPRETER_H_

#include "config.hpp"
#include "macros.hpp"
#include "String.hpp"
#include "Array.hpp"
#include "DiaPtr.h"
typedef CDiaPtr<IDiaSourceFile> IDiaSourceFilePtr;

#define A(str) encode<EncodingT,ansi>(str)
#define C(str) encode<ansi,EncodingT>(str)

using namespace boost;

NAMESPACE_BEGIN(interp)

	// Représente un fichier source.
	template <class EncodingT>
	class IDiaSourceFilePtrInterpreter
	: public Base<EncodingT>
	{
	private:
		IDiaSourceFilePtr m_object;

		void initValue(const IDiaSourceFilePtr& object);

		IDiaSourceFilePtr& value();

		const IDiaSourceFilePtr& value() const;

		void tidyValue();

	public:
		IDiaSourceFilePtrInterpreter();

		~IDiaSourceFilePtrInterpreter();

		IDiaSourceFilePtrInterpreter(const IDiaSourceFilePtr& object);

		IDiaSourceFilePtrInterpreter(const IDiaSourceFilePtrInterpreter<EncodingT>& rhs);

		IDiaSourceFilePtrInterpreter<EncodingT>& operator=(const IDiaSourceFilePtrInterpreter<EncodingT>& rhs);

		const IDiaSourceFilePtr& getValue() const;

		void setValue(IDiaSourceFilePtr const& object);

		virtual typename EncodingT::string_t toString() const;

		virtual shared_ptr< Base<EncodingT> > clone() const;

		virtual typename EncodingT::string_t getClassName() const;

		virtual shared_ptr< Base<EncodingT> > invoke(const typename EncodingT::string_t& method, std::vector< shared_ptr< Base<EncodingT> > >& params);

		// Récupère les octets de checksum.
		FACTORY_PROTOTYPE3(get_checksum, InOut< shared_ptr< Base<EncodingT> > >, InOut< shared_ptr< Base<EncodingT> > >, InOut< shared_ptr< Base<EncodingT> > >)
		shared_ptr< Base<EncodingT> > get_checksum(shared_ptr< Base<EncodingT> >& cbData, shared_ptr< Base<EncodingT> >& pcbData, shared_ptr< Base<EncodingT> >& data);

		// Extrait le nom du fichier source.
		FACTORY_PROTOTYPE1(get_fileName, InOut< shared_ptr< Base<EncodingT> > >)
		shared_ptr< Base<EncodingT> > get_fileName(shared_ptr< Base<EncodingT> >& pRetVal);

		// Récupère un énumérateur des compilands qui ont des numéros de ligne référençant ce fichier.
		FACTORY_PROTOTYPE1(get_compilands, InOut< shared_ptr< Base<EncodingT> > >)
		shared_ptr< Base<EncodingT> > get_compilands(shared_ptr< Base<EncodingT> >& ppRetVal);

		FACTORY_BEGIN_REGISTER
			CLASS_KEY_REGISTER  ( IDiaSourceFilePtrInterpreter, C("IDiaSourceFilePtr") );
			METHOD_KEY_REGISTER3( IDiaSourceFilePtrInterpreter, shared_ptr< Base<EncodingT> >, get_checksum, no_const_t, C("IDiaSourceFilePtr::Get_checksum") );
			METHOD_KEY_REGISTER1( IDiaSourceFilePtrInterpreter, shared_ptr< Base<EncodingT> >, get_fileName, no_const_t, C("IDiaSourceFilePtr::Get_fileName") );
			METHOD_KEY_REGISTER1( IDiaSourceFilePtrInterpreter, shared_ptr< Base<EncodingT> >, get_compilands, no_const_t, C("IDiaSourceFilePtr::Get_compilands") );
		FACTORY_END_REGISTER

		FACTORY_BEGIN_UNREGISTER
			CLASS_KEY_UNREGISTER  ( C("IDiaSourceFilePtr") );
			METHOD_KEY_UNREGISTER3( C("IDiaSourceFilePtr::Get_checksum") );
			METHOD_KEY_UNREGISTER1( C("IDiaSourceFilePtr::Get_fileName") );
			METHOD_KEY_UNREGISTER1( C("IDiaSourceFilePtr::Get_compilands") );
		FACTORY_END_UNREGISTER
	};

	template <class EncodingT>
	bool check_IDiaSourceFilePtr(shared_ptr< Base<EncodingT> > const& val, IDiaSourceFilePtr& a);

	template <class EncodingT>
	bool reset_IDiaSourceFilePtr(shared_ptr< Base<EncodingT> >& val, IDiaSourceFilePtr const& a);

NAMESPACE_END

#undef A
#undef C
#include "IDiaSourceFilePtrInterpreter_impl.hpp"

#endif