/*
 * IDiaEnumSymbolsPtrInterpreter.hpp
 *
 *
 * @date 21-06-2016
 * @author Teddy DIDE
 * @version 1.00
 * Pdb Interpreter generated by gensources.
 */

#ifndef _IDIAENUMSYMBOLSPTR_INTERPRETER_H_
#define _IDIAENUMSYMBOLSPTR_INTERPRETER_H_

#include "config.hpp"
#include "macros.hpp"
#include "String.hpp"
#include "Array.hpp"
#include "DiaPtr.h"
typedef CDiaPtr<IDiaEnumSymbols> IDiaEnumSymbolsPtr;
#include "IDiaSymbolPtrInterpreter.hpp"

#define A(str) encode<EncodingT,ansi>(str)
#define C(str) encode<ansi,EncodingT>(str)

using namespace boost;

NAMESPACE_BEGIN(interp)

	// Classe qui énumère les différents symboles contenus dans la source de données.
	template <class EncodingT>
	class IDiaEnumSymbolsPtrInterpreter
	: public Base<EncodingT>
	{
	private:
		IDiaEnumSymbolsPtr m_object;

		void initValue(const IDiaEnumSymbolsPtr& object);

		IDiaEnumSymbolsPtr& value();

		const IDiaEnumSymbolsPtr& value() const;

		void tidyValue();

	public:
		IDiaEnumSymbolsPtrInterpreter();

		~IDiaEnumSymbolsPtrInterpreter();

		IDiaEnumSymbolsPtrInterpreter(const IDiaEnumSymbolsPtr& object);

		IDiaEnumSymbolsPtrInterpreter(const IDiaEnumSymbolsPtrInterpreter<EncodingT>& rhs);

		IDiaEnumSymbolsPtrInterpreter<EncodingT>& operator=(const IDiaEnumSymbolsPtrInterpreter<EncodingT>& rhs);

		const IDiaEnumSymbolsPtr& getValue() const;

		void setValue(IDiaEnumSymbolsPtr const& object);

		virtual typename EncodingT::string_t toString() const;

		virtual shared_ptr< Base<EncodingT> > clone() const;

		virtual typename EncodingT::string_t getClassName() const;

		virtual shared_ptr< Base<EncodingT> > invoke(const typename EncodingT::string_t& method, std::vector< shared_ptr< Base<EncodingT> > >& params);

		// Récupère le nombre de symboles.
		FACTORY_PROTOTYPE1(get_Count, InOut< shared_ptr< Base<EncodingT> > >)
		shared_ptr< Base<EncodingT> > get_Count(shared_ptr< Base<EncodingT> >& pRetVal);

		// Récupère un symbole au moyen d'un index.
		FACTORY_PROTOTYPE2(item, In< shared_ptr< Base<EncodingT> > >, InOut< shared_ptr< Base<EncodingT> > >)
		shared_ptr< Base<EncodingT> > item(const shared_ptr< Base<EncodingT> >& index, shared_ptr< Base<EncodingT> >& symbol);

		// Récupère un nombre spécifié de symboles dans la séquence d'énumération.
		FACTORY_PROTOTYPE3(next, In< shared_ptr< Base<EncodingT> > >, InOut< shared_ptr< Base<EncodingT> > >, InOut< shared_ptr< Base<EncodingT> > >)
		shared_ptr< Base<EncodingT> > next(const shared_ptr< Base<EncodingT> >& celt, shared_ptr< Base<EncodingT> >& rgelt, shared_ptr< Base<EncodingT> >& pceltFetched);

		// Ignore un nombre spécifié de symboles dans une séquence d'énumération.
		FACTORY_PROTOTYPE1(skip, In< shared_ptr< Base<EncodingT> > >)
		shared_ptr< Base<EncodingT> > skip(const shared_ptr< Base<EncodingT> >& celt);

		// Réinitialise une séquence d'énumération au début.
		shared_ptr< Base<EncodingT> > reset();

		FACTORY_BEGIN_REGISTER
			CLASS_KEY_REGISTER  ( IDiaEnumSymbolsPtrInterpreter, C("IDiaEnumSymbolsPtr") );
			METHOD_KEY_REGISTER1( IDiaEnumSymbolsPtrInterpreter, shared_ptr< Base<EncodingT> >, get_Count, no_const_t, C("IDiaEnumSymbolsPtr::Get_Count") );
			METHOD_KEY_REGISTER2( IDiaEnumSymbolsPtrInterpreter, shared_ptr< Base<EncodingT> >, item, no_const_t, C("IDiaEnumSymbolsPtr::Item") );
			METHOD_KEY_REGISTER3( IDiaEnumSymbolsPtrInterpreter, shared_ptr< Base<EncodingT> >, next, no_const_t, C("IDiaEnumSymbolsPtr::Next") );
			METHOD_KEY_REGISTER1( IDiaEnumSymbolsPtrInterpreter, shared_ptr< Base<EncodingT> >, skip, no_const_t, C("IDiaEnumSymbolsPtr::Skip") );
			METHOD_KEY_REGISTER ( IDiaEnumSymbolsPtrInterpreter, shared_ptr< Base<EncodingT> >, reset, no_const_t, C("IDiaEnumSymbolsPtr::Reset") );
		FACTORY_END_REGISTER

		FACTORY_BEGIN_UNREGISTER
			CLASS_KEY_UNREGISTER  ( C("IDiaEnumSymbolsPtr") );
			METHOD_KEY_UNREGISTER1( C("IDiaEnumSymbolsPtr::Get_Count") );
			METHOD_KEY_UNREGISTER2( C("IDiaEnumSymbolsPtr::Item") );
			METHOD_KEY_UNREGISTER3( C("IDiaEnumSymbolsPtr::Next") );
			METHOD_KEY_UNREGISTER1( C("IDiaEnumSymbolsPtr::Skip") );
			METHOD_KEY_UNREGISTER ( C("IDiaEnumSymbolsPtr::Reset") );
		FACTORY_END_UNREGISTER
	};

	template <class EncodingT>
	bool check_IDiaEnumSymbolsPtr(shared_ptr< Base<EncodingT> > const& val, IDiaEnumSymbolsPtr& a);

	template <class EncodingT>
	bool reset_IDiaEnumSymbolsPtr(shared_ptr< Base<EncodingT> >& val, IDiaEnumSymbolsPtr const& a);

NAMESPACE_END

#undef A
#undef C
#include "IDiaEnumSymbolsPtrInterpreter_impl.hpp"

#endif