/* 
 * cppFileTypeInterpreter.hpp
 *
 *
 * @date 31-07-2022
 * @author Teddy DIDE
 * @version 1.00
 * cppBase generated by gensources.
 */

#ifndef _CPPFILETYPE_INTERPRETER_HPP_
#define _CPPFILETYPE_INTERPRETER_HPP_

#include "config.hpp"
#include "Macros.hpp"
#include "Base.hpp"
#include "Array.hpp"

#include "cppBaseExport.hpp"
#include "cppBaseData.h"
#define A(str) encode<EncodingT,ansi>(str)
#define C(str) encode<ansi,EncodingT>(str)

NAMESPACE_BEGIN(interp)

using namespace log4cpp;
using namespace fctr;
using namespace enc;
using namespace entity;
using namespace boost;

template <class EncodingT>
class CppFileInterpreter;

template <class EncodingT>
class CppFileTypeInterpreter
: public Base<EncodingT>
{
private:
	boost::shared_ptr< _CppFileType<EncodingT> > m_value;

public:
	CppFileTypeInterpreter();

	CppFileTypeInterpreter(boost::shared_ptr< _CppFileType<EncodingT> > const& value);

	FACTORY_PROTOTYPE1(CppFileTypeInterpreter,
				In< boost::shared_ptr< Base<EncodingT> > >)
	CppFileTypeInterpreter(boost::shared_ptr< Base<EncodingT> > const& string);

	boost::shared_ptr< _CppFileType<EncodingT> > value() const;

	void value(boost::shared_ptr< _CppFileType<EncodingT> > const& value);

	virtual typename EncodingT::string_t toString() const;

	virtual boost::shared_ptr< Base<EncodingT> > clone() const;

	virtual typename EncodingT::string_t getClassName() const;

	virtual boost::shared_ptr< Base<EncodingT> > invoke(const typename EncodingT::string_t& method, std::vector< boost::shared_ptr< Base<EncodingT> > >& params);

	boost::shared_ptr< Base<EncodingT> > getIdentifier() const;

	boost::shared_ptr< Base<EncodingT> > getString() const;

	FACTORY_PROTOTYPE1(setString, In< boost::shared_ptr< Base<EncodingT> > >)
	void setString(boost::shared_ptr< Base<EncodingT> > const& string);

	FACTORY_PROTOTYPE1(removeCppFile, In< boost::shared_ptr< Base<EncodingT> > >)
	void removeCppFile(boost::shared_ptr< Base<EncodingT> > const& n);

	FACTORY_PROTOTYPE2(insertCppFile, In< boost::shared_ptr< Base<EncodingT> > >, In< boost::shared_ptr< Base<EncodingT> > >)
	void insertCppFile(boost::shared_ptr< Base<EncodingT> > const& n, boost::shared_ptr< Base<EncodingT> > const& cppFile);

	FACTORY_PROTOTYPE1(getCppFile, In< boost::shared_ptr< Base<EncodingT> > >)
	boost::shared_ptr< Base<EncodingT> > getCppFile(boost::shared_ptr< Base<EncodingT> > const& n);

	void clearCppFiles();

	boost::shared_ptr< Base<EncodingT> > hasCppFiles() const;

	boost::shared_ptr< Base<EncodingT> > cppFilesCount() const;

	FACTORY_BEGIN_REGISTER
		CLASS_KEY_REGISTER ( CppFileTypeInterpreter, UCS("CppFileType") );
		CLASS_KEY_REGISTER1( CppFileTypeInterpreter, UCS("CppFileType") );
		METHOD_KEY_REGISTER ( CppFileTypeInterpreter, boost::shared_ptr< Base<EncodingT> >, getIdentifier, const_t, UCS("CppFileType::Identifier") );
		METHOD_KEY_REGISTER ( CppFileTypeInterpreter, boost::shared_ptr< Base<EncodingT> >, getString, const_t, UCS("CppFileType::String") );
		METHOD_KEY_REGISTER1( CppFileTypeInterpreter, void, setString, no_const_t, UCS("CppFileType::String") );
		METHOD_KEY_REGISTER1( CppFileTypeInterpreter, void, removeCppFile, no_const_t, UCS("CppFileType::removeCppFiles") );
		METHOD_KEY_REGISTER2( CppFileTypeInterpreter, void, insertCppFile, no_const_t, UCS("CppFileType::CppFiles") );
		METHOD_KEY_REGISTER1( CppFileTypeInterpreter, boost::shared_ptr< Base<EncodingT> >, getCppFile, no_const_t, UCS("CppFileType::CppFiles") );
		METHOD_KEY_REGISTER ( CppFileTypeInterpreter, void, clearCppFiles, no_const_t, UCS("CppFileType::ClearCppFiles") );
		METHOD_KEY_REGISTER ( CppFileTypeInterpreter, boost::shared_ptr< Base<EncodingT> >, hasCppFiles, const_t, UCS("CppFileType::HasCppFiles") );
		METHOD_KEY_REGISTER ( CppFileTypeInterpreter, boost::shared_ptr< Base<EncodingT> >, cppFilesCount, const_t, UCS("CppFileType::CppFilesCount") );
	FACTORY_END_REGISTER

	FACTORY_BEGIN_UNREGISTER
		CLASS_KEY_UNREGISTER ( UCS("CppFileType") );
		CLASS_KEY_UNREGISTER1( UCS("CppFileType") );
		METHOD_KEY_UNREGISTER ( UCS("CppFileType::Identifier") );
		METHOD_KEY_UNREGISTER ( UCS("CppFileType::String") );
		METHOD_KEY_UNREGISTER1( UCS("CppFileType::String") );
		METHOD_KEY_UNREGISTER1( UCS("CppFileType::removeCppFiles") );
		METHOD_KEY_UNREGISTER2( UCS("CppFileType::CppFiles") );
		METHOD_KEY_UNREGISTER1( UCS("CppFileType::CppFiles") );
		METHOD_KEY_UNREGISTER ( UCS("CppFileType::ClearCppFiles") );
		METHOD_KEY_UNREGISTER ( UCS("CppFileType::HasCppFiles") );
		METHOD_KEY_UNREGISTER ( UCS("CppFileType::CppFilesCount") );
	FACTORY_END_UNREGISTER
};

template <class EncodingT>
bool check_cppFileType(boost::shared_ptr< Base<EncodingT> > const& val, boost::shared_ptr< _CppFileType<EncodingT> >& o);

template <class EncodingT>
bool reset_cppFileType(boost::shared_ptr< Base<EncodingT> >& val, boost::shared_ptr< _CppFileType<EncodingT> > const& o);

NAMESPACE_END

#undef C
#undef A

#include "cppFileTypeInterpreter_impl.hpp"

#endif
