/* 
 * cppParameterInterpreterAccess.hpp
 *
 *
 * @date 10-05-2020
 * @author Teddy DIDE
 * @version 1.00
 * cppBase generated by gensources.
 */

#ifndef _CPPPARAMETER_INTERPRETER_ACCESS_HPP_
#define _CPPPARAMETER_INTERPRETER_ACCESS_HPP_

#include "config.hpp"
#include "Macros.hpp"
#include "String.hpp"

#include "cppBaseExport.hpp"
#include "cppBaseData.h"
#define A(str) encode<EncodingT,ansi>(str)
#define C(str) encode<ansi,EncodingT>(str)

NAMESPACE_BEGIN(interp)

using namespace log4cpp;
using namespace fctr;
using namespace enc;
using namespace data_access;
using namespace boost;

template <class EncodingT>
class CppParameterInterpreterAccess
: public Base<EncodingT>
{
private:
	_CppParameterAccess<EncodingT>* m_object;
	std::string m_errorText;
	bool m_error;

public:
	CppParameterInterpreterAccess();

	virtual typename EncodingT::string_t toString() const;

	virtual boost::shared_ptr< Base<EncodingT> > clone() const;

	virtual typename EncodingT::string_t getClassName() const;

	virtual boost::shared_ptr< Base<EncodingT> > invoke(const typename EncodingT::string_t& method, std::vector< boost::shared_ptr< Base<EncodingT> > >& params);

	boost::shared_ptr< Base<EncodingT> > getAllCppParameters();

	FACTORY_PROTOTYPE1(getManyCppParameters, In< boost::shared_ptr< Base<EncodingT> > >)
	boost::shared_ptr< Base<EncodingT> > getManyCppParameters(const boost::shared_ptr< Base<EncodingT> >& filter);

	FACTORY_PROTOTYPE1(getOneCppParameter,
				In< boost::shared_ptr< Base<EncodingT> > >)
	boost::shared_ptr< Base<EncodingT> > getOneCppParameter(boost::shared_ptr< Base<EncodingT> > const& identifier);

	FACTORY_PROTOTYPE2(selectOneCppParameter,
				In< boost::shared_ptr< Base<EncodingT> > >,
				In< boost::shared_ptr< Base<EncodingT> > >)
	boost::shared_ptr< Base<EncodingT> > selectOneCppParameter(boost::shared_ptr< Base<EncodingT> > const& identifier,
				const boost::shared_ptr< Base<EncodingT> >& nowait);

	FACTORY_PROTOTYPE2(selectManyCppParameters, In< boost::shared_ptr< Base<EncodingT> > >, In< boost::shared_ptr< Base<EncodingT> > >)
	boost::shared_ptr< Base<EncodingT> > selectManyCppParameters(const boost::shared_ptr< Base<EncodingT> >& filter, const boost::shared_ptr< Base<EncodingT> >& nowait);

	void cancelSelection();

	FACTORY_PROTOTYPE1(isSelectedCppParameter, In< boost::shared_ptr< Base<EncodingT> > >)
	boost::shared_ptr< Base<EncodingT> > isSelectedCppParameter(const boost::shared_ptr< Base<EncodingT> >& cppParameter);

	FACTORY_PROTOTYPE1(fillCppFunction, InOut< boost::shared_ptr< Base<EncodingT> > >)
	void fillCppFunction(boost::shared_ptr< Base<EncodingT> >& cppParameter);

	FACTORY_PROTOTYPE1(isModifiedCppParameter, In< boost::shared_ptr< Base<EncodingT> > >)
	boost::shared_ptr< Base<EncodingT> > isModifiedCppParameter(const boost::shared_ptr< Base<EncodingT> >& cppParameter);

	FACTORY_PROTOTYPE1(updateCppParameter, InOut< boost::shared_ptr< Base<EncodingT> > >)
	void updateCppParameter(boost::shared_ptr< Base<EncodingT> >& cppParameter);

	FACTORY_PROTOTYPE1(insertCppParameter, InOut< boost::shared_ptr< Base<EncodingT> > >)
	void insertCppParameter(boost::shared_ptr< Base<EncodingT> >& cppParameter);

	FACTORY_PROTOTYPE1(deleteCppParameter, InOut< boost::shared_ptr< Base<EncodingT> > >)
	void deleteCppParameter(boost::shared_ptr< Base<EncodingT> >& cppParameter);

	void setError(const std::exception& e);

	void clearError();

	FACTORY_PROTOTYPE1(getError, InOut< boost::shared_ptr< Base<EncodingT> > >)
	boost::shared_ptr< Base<EncodingT> > getError(boost::shared_ptr< Base<EncodingT> >& text) const;

	FACTORY_BEGIN_REGISTER
		CLASS_KEY_REGISTER ( CppParameterInterpreterAccess, UCS("CppParameterAccess") );
		METHOD_KEY_REGISTER ( CppParameterInterpreterAccess, boost::shared_ptr< Base<EncodingT> >, getAllCppParameters, no_const_t, UCS("CppParameterAccess::GetAllCppParameters") );
		METHOD_KEY_REGISTER1( CppParameterInterpreterAccess, boost::shared_ptr< Base<EncodingT> >, getManyCppParameters, no_const_t, UCS("CppParameterAccess::GetManyCppParameters") );
		METHOD_KEY_REGISTER1( CppParameterInterpreterAccess, boost::shared_ptr< Base<EncodingT> >, getOneCppParameter, no_const_t, UCS("CppParameterAccess::GetOneCppParameter") );
		METHOD_KEY_REGISTER2( CppParameterInterpreterAccess, boost::shared_ptr< Base<EncodingT> >, selectOneCppParameter, no_const_t, UCS("CppParameterAccess::SelectOneCppParameter") );
		METHOD_KEY_REGISTER2( CppParameterInterpreterAccess, boost::shared_ptr< Base<EncodingT> >, selectManyCppParameters, no_const_t, UCS("CppParameterAccess::SelectManyCppParameters") );
		METHOD_KEY_REGISTER ( CppParameterInterpreterAccess, void, cancelSelection, no_const_t, UCS("CppParameterAccess::CancelSelection") );
		METHOD_KEY_REGISTER1( CppParameterInterpreterAccess, boost::shared_ptr< Base<EncodingT> >, isSelectedCppParameter, no_const_t, UCS("CppParameterAccess::IsSelectedCppParameter") );
		METHOD_KEY_REGISTER1( CppParameterInterpreterAccess, void, fillCppFunction, no_const_t, UCS("CppParameterAccess::FillCppFunction") );
		METHOD_KEY_REGISTER1( CppParameterInterpreterAccess, boost::shared_ptr< Base<EncodingT> >, isModifiedCppParameter, no_const_t, UCS("CppParameterAccess::IsModifiedCppParameter") );
		METHOD_KEY_REGISTER1( CppParameterInterpreterAccess, void, updateCppParameter, no_const_t, UCS("CppParameterAccess::UpdateCppParameter") );
		METHOD_KEY_REGISTER1( CppParameterInterpreterAccess, void, insertCppParameter, no_const_t, UCS("CppParameterAccess::InsertCppParameter") );
		METHOD_KEY_REGISTER1( CppParameterInterpreterAccess, void, deleteCppParameter, no_const_t, UCS("CppParameterAccess::DeleteCppParameter") );
		METHOD_KEY_REGISTER1( CppParameterInterpreterAccess, boost::shared_ptr< Base<EncodingT> >, getError, const_t, UCS("CppParameterAccess::GetError") );
	FACTORY_END_REGISTER

	FACTORY_BEGIN_UNREGISTER
		CLASS_KEY_UNREGISTER ( UCS("CppParameterAccess") );
		METHOD_KEY_UNREGISTER ( UCS("CppParameterAccess::GetAllCppParameters") );
		METHOD_KEY_UNREGISTER1( UCS("CppParameterAccess::GetManyCppParameters") );
		METHOD_KEY_UNREGISTER1( UCS("CppParameterAccess::GetOneCppParameter") );
		METHOD_KEY_UNREGISTER2( UCS("CppParameterAccess::SelectOneCppParameter") );
		METHOD_KEY_UNREGISTER2( UCS("CppParameterAccess::SelectManyCppParameters") );
		METHOD_KEY_UNREGISTER ( UCS("CppParameterAccess::CancelSelection") );
		METHOD_KEY_UNREGISTER1( UCS("CppParameterAccess::IsSelectedCppParameter") );
		METHOD_KEY_UNREGISTER1( UCS("CppParameterAccess::FillCppFunction") );
		METHOD_KEY_UNREGISTER1( UCS("CppParameterAccess::IsModifiedCppParameter") );
		METHOD_KEY_UNREGISTER1( UCS("CppParameterAccess::UpdateCppParameter") );
		METHOD_KEY_UNREGISTER1( UCS("CppParameterAccess::InsertCppParameter") );
		METHOD_KEY_UNREGISTER1( UCS("CppParameterAccess::DeleteCppParameter") );
		METHOD_KEY_UNREGISTER1( UCS("CppParameterAccess::GetError") );
	FACTORY_END_UNREGISTER

	boost::shared_ptr< Base<EncodingT> > convert_array(const std::vector< boost::shared_ptr< _CppParameter<EncodingT> > >& value) const;
};

NAMESPACE_END

#undef C
#undef A

#include "cppParameterInterpreterAccess_impl.hpp"

#endif
