/*
 * CreateFlagsInterpreter.hpp
 *
 *
 * @date 20-10-2018
 * @author Teddy DIDE
 * @version 1.00
 * Debug Interpreter generated by gensources.
 */

#ifndef _CREATEFLAGS_INTERPRETER_H_
#define _CREATEFLAGS_INTERPRETER_H_

#include "config.hpp"
#include "macros.hpp"
#include "Base.hpp"
#include "Array.hpp"


#define A(str) encode<EncodingT,ansi>(str)
#define C(str) encode<ansi,EncodingT>(str)

using namespace boost;

NAMESPACE_BEGIN(interp)

	template <class EncodingT>
	class CreateFlagsInterpreter
	: public Base<EncodingT>
	{
	private:

		void tidyValue();

	public:
		CreateFlagsInterpreter();

		~CreateFlagsInterpreter();

		virtual typename EncodingT::string_t toString() const;

		virtual boost::shared_ptr< Base<EncodingT> > clone() const;

		virtual typename EncodingT::string_t getClassName() const;

		virtual boost::shared_ptr< Base<EncodingT> > invoke(const typename EncodingT::string_t& method, std::vector< boost::shared_ptr< Base<EncodingT> > >& params);

		boost::shared_ptr< Base<EncodingT> > getDEBUG_PROCESS() const;

		boost::shared_ptr< Base<EncodingT> > getDEBUG_ONLY_THIS_PROCESS() const;

		FACTORY_BEGIN_REGISTER
			CLASS_KEY_REGISTER  ( CreateFlagsInterpreter, C("CreateFlags") );
			METHOD_KEY_REGISTER ( CreateFlagsInterpreter, boost::shared_ptr< Base<EncodingT> >, getDEBUG_PROCESS, const_t, C("CreateFlags::DEBUG_PROCESS") );
			METHOD_KEY_REGISTER ( CreateFlagsInterpreter, boost::shared_ptr< Base<EncodingT> >, getDEBUG_ONLY_THIS_PROCESS, const_t, C("CreateFlags::DEBUG_ONLY_THIS_PROCESS") );
		FACTORY_END_REGISTER

		FACTORY_BEGIN_UNREGISTER
			CLASS_KEY_UNREGISTER  ( C("CreateFlags") );
			METHOD_KEY_UNREGISTER ( C("CreateFlags::DEBUG_PROCESS") );
			METHOD_KEY_UNREGISTER ( C("CreateFlags::DEBUG_ONLY_THIS_PROCESS") );
		FACTORY_END_UNREGISTER
	};

NAMESPACE_END

#undef A
#undef C
#include "CreateFlagsInterpreter_impl.hpp"

#endif