/*
 * IDebugBreakpointPtrInterpreter.hpp
 *
 *
 * @date 12-07-2020
 * @author Teddy DIDE
 * @version 1.00
 * Debug Interpreter generated by gensources.
 */

#ifndef _IDEBUGBREAKPOINTPTR_INTERPRETER_H_
#define _IDEBUGBREAKPOINTPTR_INTERPRETER_H_

#include "config.hpp"
#include "Macros.hpp"
#include "Base.hpp"
#include "Array.hpp"
#include "DebugPtr.h"
typedef IDebugBreakpoint* IDebugBreakpointPtr;

#define A(str) encode<EncodingT,ansi>(str)
#define C(str) encode<ansi,EncodingT>(str)

using namespace boost;

NAMESPACE_BEGIN(interp)

	// Classe permettant d'accéder aux informations d'un breakpoint.
	template <class EncodingT>
	class IDebugBreakpointPtrInterpreter
	: public Base<EncodingT>
	{
	private:
		IDebugBreakpointPtr m_object;

		void initValue(const IDebugBreakpointPtr& object);

		IDebugBreakpointPtr& refValue();

		const IDebugBreakpointPtr& refValue() const;

		void tidyValue();

	public:
		IDebugBreakpointPtrInterpreter();

		IDebugBreakpointPtrInterpreter(const IDebugBreakpointPtr& object);

		const IDebugBreakpointPtr& value() const;

		void value(IDebugBreakpointPtr const& object);

		virtual typename EncodingT::string_t toString() const;

		virtual boost::shared_ptr< Base<EncodingT> > clone() const;

		virtual typename EncodingT::string_t getClassName() const;

		virtual boost::shared_ptr< Base<EncodingT> > invoke(const typename EncodingT::string_t& method, std::vector< boost::shared_ptr< Base<EncodingT> > >& params);

		// Sets the location that triggers a breakpoint.
		FACTORY_PROTOTYPE1(setOffset, In< boost::shared_ptr< Base<EncodingT> > >)
		boost::shared_ptr< Base<EncodingT> > setOffset(const boost::shared_ptr< Base<EncodingT> >& offset);

		// The SetOffsetExpression methods set an expression string that evaluates to the location that triggers a breakpoint.
		FACTORY_PROTOTYPE1(setOffsetExpression, In< boost::shared_ptr< Base<EncodingT> > >)
		boost::shared_ptr< Base<EncodingT> > setOffsetExpression(const boost::shared_ptr< Base<EncodingT> >& expression);

		// Sets the flags for a breakpoint.
		FACTORY_PROTOTYPE1(setFlags, In< boost::shared_ptr< Base<EncodingT> > >)
		boost::shared_ptr< Base<EncodingT> > setFlags(const boost::shared_ptr< Base<EncodingT> >& flags);

		// The SetPassCount method sets the number of times that the target must reach the breakpoint location before the breakpoint is triggered.
		FACTORY_PROTOTYPE1(setPassCount, In< boost::shared_ptr< Base<EncodingT> > >)
		boost::shared_ptr< Base<EncodingT> > setPassCount(const boost::shared_ptr< Base<EncodingT> >& count);

		// The GetPassCount method returns the number of times that the target was originally required to reach the breakpoint location before the breakpoint is triggered.
		FACTORY_PROTOTYPE1(getPassCount, InOut< boost::shared_ptr< Base<EncodingT> > >)
		boost::shared_ptr< Base<EncodingT> > getPassCount(boost::shared_ptr< Base<EncodingT> >& count);

		// The GetCurrentPassCount method returns the remaining number of times that the target must reach the breakpoint location before the breakpoint is triggered.
		FACTORY_PROTOTYPE1(getCurrentPassCount, InOut< boost::shared_ptr< Base<EncodingT> > >)
		boost::shared_ptr< Base<EncodingT> > getCurrentPassCount(boost::shared_ptr< Base<EncodingT> >& count);

		// The GetId method returns a breakpoint ID, which is the engine's unique identifier for a breakpoint.
		FACTORY_PROTOTYPE1(getId, InOut< boost::shared_ptr< Base<EncodingT> > >)
		boost::shared_ptr< Base<EncodingT> > getId(boost::shared_ptr< Base<EncodingT> >& bpId);

		// The GetOffset method returns the location that triggers a breakpoint.
		FACTORY_PROTOTYPE1(getOffset, InOut< boost::shared_ptr< Base<EncodingT> > >)
		boost::shared_ptr< Base<EncodingT> > getOffset(boost::shared_ptr< Base<EncodingT> >& offset);

		FACTORY_BEGIN_REGISTER
			CLASS_KEY_REGISTER  ( IDebugBreakpointPtrInterpreter, UCS("IDebugBreakpointPtr") );
			METHOD_KEY_REGISTER1( IDebugBreakpointPtrInterpreter, boost::shared_ptr< Base<EncodingT> >, setOffset, no_const_t, UCS("IDebugBreakpointPtr::SetOffset") );
			METHOD_KEY_REGISTER1( IDebugBreakpointPtrInterpreter, boost::shared_ptr< Base<EncodingT> >, setOffsetExpression, no_const_t, UCS("IDebugBreakpointPtr::SetOffsetExpression") );
			METHOD_KEY_REGISTER1( IDebugBreakpointPtrInterpreter, boost::shared_ptr< Base<EncodingT> >, setFlags, no_const_t, UCS("IDebugBreakpointPtr::SetFlags") );
			METHOD_KEY_REGISTER1( IDebugBreakpointPtrInterpreter, boost::shared_ptr< Base<EncodingT> >, setPassCount, no_const_t, UCS("IDebugBreakpointPtr::SetPassCount") );
			METHOD_KEY_REGISTER1( IDebugBreakpointPtrInterpreter, boost::shared_ptr< Base<EncodingT> >, getPassCount, no_const_t, UCS("IDebugBreakpointPtr::GetPassCount") );
			METHOD_KEY_REGISTER1( IDebugBreakpointPtrInterpreter, boost::shared_ptr< Base<EncodingT> >, getCurrentPassCount, no_const_t, UCS("IDebugBreakpointPtr::GetCurrentPassCount") );
			METHOD_KEY_REGISTER1( IDebugBreakpointPtrInterpreter, boost::shared_ptr< Base<EncodingT> >, getId, no_const_t, UCS("IDebugBreakpointPtr::GetId") );
			METHOD_KEY_REGISTER1( IDebugBreakpointPtrInterpreter, boost::shared_ptr< Base<EncodingT> >, getOffset, no_const_t, UCS("IDebugBreakpointPtr::GetOffset") );
		FACTORY_END_REGISTER

		FACTORY_BEGIN_UNREGISTER
			CLASS_KEY_UNREGISTER  ( UCS("IDebugBreakpointPtr") );
			METHOD_KEY_UNREGISTER1( UCS("IDebugBreakpointPtr::SetOffset") );
			METHOD_KEY_UNREGISTER1( UCS("IDebugBreakpointPtr::SetOffsetExpression") );
			METHOD_KEY_UNREGISTER1( UCS("IDebugBreakpointPtr::SetFlags") );
			METHOD_KEY_UNREGISTER1( UCS("IDebugBreakpointPtr::SetPassCount") );
			METHOD_KEY_UNREGISTER1( UCS("IDebugBreakpointPtr::GetPassCount") );
			METHOD_KEY_UNREGISTER1( UCS("IDebugBreakpointPtr::GetCurrentPassCount") );
			METHOD_KEY_UNREGISTER1( UCS("IDebugBreakpointPtr::GetId") );
			METHOD_KEY_UNREGISTER1( UCS("IDebugBreakpointPtr::GetOffset") );
		FACTORY_END_UNREGISTER
	};

	template <class EncodingT>
	bool check_IDebugBreakpointPtr(boost::shared_ptr< Base<EncodingT> > const& val, IDebugBreakpointPtr& a);

	template <class EncodingT>
	bool reset_IDebugBreakpointPtr(boost::shared_ptr< Base<EncodingT> >& val, IDebugBreakpointPtr const& a);

NAMESPACE_END

#undef A
#undef C
#include "IDebugBreakpointPtrInterpreter_impl.hpp"

#endif