/*
 * ImageFileMachineInterpreter_impl.hpp
 *
 *
 * @date 21-06-2016
 * @author Teddy DIDE
 * @version 1.00
 * Debug Interpreter generated by gensources.
 */

#define A(str) encode<EncodingT,ansi>(str)
#define C(str) encode<ansi,EncodingT>(str)

NAMESPACE_BEGIN(interp)


template <class EncodingT>
ImageFileMachineInterpreter<EncodingT>::ImageFileMachineInterpreter()
{
}

template <class EncodingT>
void ImageFileMachineInterpreter<EncodingT>::tidyValue()
{
}

template <class EncodingT>
ImageFileMachineInterpreter<EncodingT>::~ImageFileMachineInterpreter()
{
	tidyValue();
}

template <class EncodingT>
typename EncodingT::string_t ImageFileMachineInterpreter<EncodingT>::toString() const
{
	return EncodingT::EMPTY;
}

template <class EncodingT>
shared_ptr< Base<EncodingT> > ImageFileMachineInterpreter<EncodingT>::clone() const
{
	return shared_ptr< Base<EncodingT> >(new ImageFileMachineInterpreter<EncodingT>(*this));
}

template <class EncodingT>
typename EncodingT::string_t ImageFileMachineInterpreter<EncodingT>::getClassName() const
{
	return C("ImageFileMachine");
}

template <class EncodingT>
shared_ptr< Base<EncodingT> > ImageFileMachineInterpreter<EncodingT>::invoke(const typename EncodingT::string_t& method, std::vector< shared_ptr< Base<EncodingT> > >& params)
{
	shared_ptr< Base<EncodingT> > obj(new Base<EncodingT>());
	ParameterArray args, ret;
	if (check_parameters_array(params, args))
	{
		if (tryInvoke(this, C("ImageFileMachine"), method, args, ret))
		{
			find_parameter(ret, FACTORY_RETURN_PARAMETER, obj);
			for (size_t i = 0; i < params.size(); ++i)
			{
				find_parameter(ret, i, params[i]);
			}
		}
		else
		{
			Category* logger = &Category::getInstance(LOGNAME);
			logger->errorStream() << "Unexpected call in ImageFileMachine, no method \"" << A(method) << "\" exists.";
		}
	}
	return obj;
}

template <class EncodingT>
shared_ptr< Base<EncodingT> > ImageFileMachineInterpreter<EncodingT>::getIMAGE_FILE_MACHINE_AM33() const
{
	return shared_ptr< Base<EncodingT> > (new Numeric<EncodingT>(IMAGE_FILE_MACHINE_AM33));
}

template <class EncodingT>
shared_ptr< Base<EncodingT> > ImageFileMachineInterpreter<EncodingT>::getIMAGE_FILE_MACHINE_AMD64() const
{
	return shared_ptr< Base<EncodingT> > (new Numeric<EncodingT>(IMAGE_FILE_MACHINE_AMD64));
}

template <class EncodingT>
shared_ptr< Base<EncodingT> > ImageFileMachineInterpreter<EncodingT>::getIMAGE_FILE_MACHINE_ARM() const
{
	return shared_ptr< Base<EncodingT> > (new Numeric<EncodingT>(IMAGE_FILE_MACHINE_ARM));
}

template <class EncodingT>
shared_ptr< Base<EncodingT> > ImageFileMachineInterpreter<EncodingT>::getIMAGE_FILE_MACHINE_ARMV7() const
{
	return shared_ptr< Base<EncodingT> > (new Numeric<EncodingT>(IMAGE_FILE_MACHINE_ARMV7));
}

template <class EncodingT>
shared_ptr< Base<EncodingT> > ImageFileMachineInterpreter<EncodingT>::getIMAGE_FILE_MACHINE_EBC() const
{
	return shared_ptr< Base<EncodingT> > (new Numeric<EncodingT>(IMAGE_FILE_MACHINE_EBC));
}

template <class EncodingT>
shared_ptr< Base<EncodingT> > ImageFileMachineInterpreter<EncodingT>::getIMAGE_FILE_MACHINE_I386() const
{
	return shared_ptr< Base<EncodingT> > (new Numeric<EncodingT>(IMAGE_FILE_MACHINE_I386));
}

template <class EncodingT>
shared_ptr< Base<EncodingT> > ImageFileMachineInterpreter<EncodingT>::getIMAGE_FILE_MACHINE_IA64() const
{
	return shared_ptr< Base<EncodingT> > (new Numeric<EncodingT>(IMAGE_FILE_MACHINE_IA64));
}

template <class EncodingT>
shared_ptr< Base<EncodingT> > ImageFileMachineInterpreter<EncodingT>::getIMAGE_FILE_MACHINE_M32R() const
{
	return shared_ptr< Base<EncodingT> > (new Numeric<EncodingT>(IMAGE_FILE_MACHINE_M32R));
}

template <class EncodingT>
shared_ptr< Base<EncodingT> > ImageFileMachineInterpreter<EncodingT>::getIMAGE_FILE_MACHINE_MIPS16() const
{
	return shared_ptr< Base<EncodingT> > (new Numeric<EncodingT>(IMAGE_FILE_MACHINE_MIPS16));
}

template <class EncodingT>
shared_ptr< Base<EncodingT> > ImageFileMachineInterpreter<EncodingT>::getIMAGE_FILE_MACHINE_MIPSFPU() const
{
	return shared_ptr< Base<EncodingT> > (new Numeric<EncodingT>(IMAGE_FILE_MACHINE_MIPSFPU));
}

template <class EncodingT>
shared_ptr< Base<EncodingT> > ImageFileMachineInterpreter<EncodingT>::getIMAGE_FILE_MACHINE_MIPSFPU16() const
{
	return shared_ptr< Base<EncodingT> > (new Numeric<EncodingT>(IMAGE_FILE_MACHINE_MIPSFPU16));
}

template <class EncodingT>
shared_ptr< Base<EncodingT> > ImageFileMachineInterpreter<EncodingT>::getIMAGE_FILE_MACHINE_POWERPC() const
{
	return shared_ptr< Base<EncodingT> > (new Numeric<EncodingT>(IMAGE_FILE_MACHINE_POWERPC));
}


NAMESPACE_END

#undef A
#undef C