/*
 * WaitFlagsInterpreter_impl.hpp
 *
 *
 * @date 21-06-2016
 * @author Teddy DIDE
 * @version 1.00
 * Debug Interpreter generated by gensources.
 */

#define A(str) encode<EncodingT,ansi>(str)
#define C(str) encode<ansi,EncodingT>(str)

NAMESPACE_BEGIN(interp)


template <class EncodingT>
WaitFlagsInterpreter<EncodingT>::WaitFlagsInterpreter()
{
}

template <class EncodingT>
void WaitFlagsInterpreter<EncodingT>::tidyValue()
{
}

template <class EncodingT>
WaitFlagsInterpreter<EncodingT>::~WaitFlagsInterpreter()
{
	tidyValue();
}

template <class EncodingT>
typename EncodingT::string_t WaitFlagsInterpreter<EncodingT>::toString() const
{
	return EncodingT::EMPTY;
}

template <class EncodingT>
shared_ptr< Base<EncodingT> > WaitFlagsInterpreter<EncodingT>::clone() const
{
	return shared_ptr< Base<EncodingT> >(new WaitFlagsInterpreter<EncodingT>(*this));
}

template <class EncodingT>
typename EncodingT::string_t WaitFlagsInterpreter<EncodingT>::getClassName() const
{
	return C("WaitFlags");
}

template <class EncodingT>
shared_ptr< Base<EncodingT> > WaitFlagsInterpreter<EncodingT>::invoke(const typename EncodingT::string_t& method, std::vector< shared_ptr< Base<EncodingT> > >& params)
{
	shared_ptr< Base<EncodingT> > obj(new Base<EncodingT>());
	ParameterArray args, ret;
	if (check_parameters_array(params, args))
	{
		if (tryInvoke(this, C("WaitFlags"), method, args, ret))
		{
			find_parameter(ret, FACTORY_RETURN_PARAMETER, obj);
			for (size_t i = 0; i < params.size(); ++i)
			{
				find_parameter(ret, i, params[i]);
			}
		}
		else
		{
			Category* logger = &Category::getInstance(LOGNAME);
			logger->errorStream() << "Unexpected call in WaitFlags, no method \"" << A(method) << "\" exists.";
		}
	}
	return obj;
}

template <class EncodingT>
shared_ptr< Base<EncodingT> > WaitFlagsInterpreter<EncodingT>::getDEBUG_WAIT_DEFAULT() const
{
	return shared_ptr< Base<EncodingT> > (new Numeric<EncodingT>(DEBUG_WAIT_DEFAULT));
}


NAMESPACE_END

#undef A
#undef C